name: Set up environment
description: Sets up a number of environment variables that are useful for publishing
runs:
  using: "composite"
  steps:
    - name: Determine Publish Environment
      shell: bash
      run: python3 ./.github/scripts/setup_publish_env.py
